//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminEmpleadosEF {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Readme : global::System.Configuration.ApplicationSettingsBase {
        
        private static Readme defaultInstance = ((Readme)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Readme())));
        
        public static Readme Default {
            get {
                return defaultInstance;
            }
        }
    }
}
