// <auto-generated />
using System;
using AdminEmpleadosEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminEmpleadosEF.Migrations
{
    [DbContext(typeof(AdminEmpleadosDBContext))]
    [Migration("20230928200923_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdminEmpleadosEntidades.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartamentoId"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dpto_nro")
                        .HasColumnType("int");

                    b.HasKey("DepartamentoId");

                    b.ToTable("departamento");
                });

            modelBuilder.Entity("AdminEmpleadosEntidades.Empleado", b =>
                {
                    b.Property<int?>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("EmpleadoId"));

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("dpto_id")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("dpto_id");

                    b.ToTable("empleado");
                });

            modelBuilder.Entity("AdminEmpleadosEntidades.Empleado", b =>
                {
                    b.HasOne("AdminEmpleadosEntidades.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("dpto_id");

                    b.Navigation("Departamento");
                });
#pragma warning restore 612, 618
        }
    }
}
